### ISSUE TITLE
Bad Request: /notify/apprise in Docker

### ISSUE THREAD

**Issue by jotka** [caronc/apprise-api#169] opened 2024-01-31 04:49 UTC
:question: **Question**

I've started apprise with docker:

`docker run --name=apprise volume=/docker/apprise:/config  --restart=unless-stopped --detach=true   caronc/apprise:latest
`

When I click the send Send Notification in the UI, I get Failed to send the notification(s).Bad attachment", no matter what services I have configured. I'm not adding any attachment to the test notification.

In the logs:

```
[pid: 148|app: 0|req: 4/4] 172.18.0.6 () {46 vars in 846 bytes} [Tue Jan 30 22:43:26 2024] GET /json/urls/apprise/?privacy=1 => generated 190 bytes in 120 msecs (HTTP/1.1 200) 5 headers in 274 bytes (1 switches on core 0)

[pid: 148|app: 0|req: 5/5] 172.18.0.6 () {52 vars in 917 bytes} [Tue Jan 30 22:43:27 2024] POST /get/apprise => generated 94 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 273 bytes (1 switches on core 0)

2024-01-30 22:43:38,843 [WARNING] django: NOTIFY - 172.18.0.6 - Bad attachment specified

2024-01-30 22:43:38,844 [WARNING] django.request: Bad Request: /notify/apprise
[pid: 148|app: 0|req: 6/6] 172.18.0.6 () {54 vars in 1002 bytes} [Tue Jan 30 22:43:38 2024] POST /notify/apprise => generated 14 bytes in 4 msecs (HTTP/1.1 400) 5 headers in 290 bytes (1 switches on core 0)
```

**Comment by caronc** [comment] 2024-02-01 02:41
This is a duplicate of #168 and has been rectified now.  Make sure you pull the `:latest` branch just pushed (v0.9.9)

**Comment by caronc** [comment] 2024-02-04 18:40
Closing issue off as it has been resolved now.

**Closed by caronc** 2024-02-04 18:40 UTC
Labels: question
