### ISSUE TITLE
Does the api support ntfy file attachments? 

### ISSUE THREAD

**Issue by gorrilla10101** [caronc/apprise-api#157] opened 2023-12-24 03:00 UTC
:question: **Question**

I looked through the documentation for ntfy on apprise and it appears that you are supposed to pass attach to get an image from a url. When calling the API, I can't seem to get it to work. 

Here is an example curl 
```
 curl 'https://{url_to_apprise_api}/notify/apprise' --header 'Content-Type: application/json' --data '{
    "tag": "testing",
    "title": "test",
    "body": "body",
    "attach": "{url_to_image}"

}'
```

**Comment by caronc** [comment] 2023-12-24 03:44
Try this:
```bash
curl -X POST \
    -F 'urls=ntfy://details ' \
    -F 'body=test message' \
    -F attach=@Screenshot-1.png \
    http://localhost:8000/notify
```

If you've saved your configuration in the API, then:
```bash
curl -X POST \
    -F 'body=test message' \
    -F attach=@Screenshot-1.png \
    http://localhost:8000/notify/{key}/
```

**Comment by caronc** [comment] 2024-01-27 19:04
I haven't heard back in a while, so i'm closing off this ticket

**Comment by flinthamm** [comment] 2024-02-03 12:54
Hi @caronc and first off, thanks for building this brilliant project and the ongoing development. 
In terms of this issue, is there any reason why you do not give an external url in your examples (as per @gorrilla10101), as this works correctly if you use the Ntfy API directly but not through your Apprise API? I've tried using "attach" as a post field and using a JSON string but the picture does not appear in the push message,
It also seems to ignore "Markdown" regardless of putting the Markdown field set to "yes" in either the header, as a field or in a JSON string.

**Comment by caronc** [comment] 2024-02-03 13:59
Hi @flinthamm,

The markdown feature i hadn't realized it even existed, so I [plan to solve this one, no worries here](https://github.com/caronc/apprise/issues/1053).

As for the attachments not working from the testing API, I'll give it a look and keep you posted. I'll reopen this ticket.

**Comment by caronc** [comment] 2024-02-03 18:55
@flinthamm I merged the `markdown` support into Apprise.  It won't show into the Apprise API for a wee bit until i can get another release going.  However there are instructions in the `Dockerfile` attached with this project you can uncomment and build against the latest Apprise branch if you need it sooner.

As per the second issue with Attachments:
1. I took the latest version of the Apprise API off of docker and started it up.  I attached an image using just the testing area of the API and uploaded it successfully (sending it off to `ntfy://` as the end point):<br/>
![Prep](https://github.com/caronc/apprise-api/assets/850374/ecaede3a-d8b6-4328-bafb-6cb7fdd80679)
2. Then i opened up Ntfy on my phone and there the image was delivered properly:<br/>
![Screenshot_20240203-134552](https://github.com/caronc/apprise-api/assets/850374/deb42e39-fa74-44ff-b4a7-84d58a703e93)

Can you share with me what you may be doing differently?  I can't seem to reproduce your issue.

**Comment by GMNDS** [comment] 2024-02-13 23:20
Hi @caronc  I recently discovered apprise and tried several ways to use the api with curl to send an attachment.

The way shown above really works, my intention is to use urls so I haven't tried it with local files outside the web ui.

Using this command does not work:

```bash
curl -X POST -F 'urls=ntfy://ntfy.mydomain.tld/test123' \
    -F 'title=test title' \
    -F 'body=test body' \
    -F attach=https://raw.githubusercontent.com/walkxcode/dashboard-icons/0eaf38572d4b8a2485228eb5da98d356ca47f653/svg/uptime-kuma.svg \
    "https://appr.mydomain.tld/notify/"
```
the result is:

![image](https://github.com/caronc/apprise-api/assets/138012112/adcf4d9c-e2ca-4567-b64c-1bf862c52fb8)

**Comment by GMNDS** [comment] 2024-02-13 23:35
Hi @caronc I recently discovered Apprise and it's an amazing tool, thanks for creating this. I'm trying the same problem using curl, to send an attachment.


The way shown above really works. However, the problem is when using curl with urls specifically (I haven't tried it with files, as I don't think I will need it)

Using this command does not work:

```bash
curl -X POST -F 'urls=ntfy://ntfy.mydomain.tld/test123' \
    -F 'title=test title' \
    -F 'body=test body' \
    -F attach=https://raw.githubusercontent.com/walkxcode/dashboard-icons/0eaf38572d4b8a2485228eb5da98d356ca47f653/svg/uptime-kuma.svg \
    "https://appr.mydomain.tld/notify/"
```
the result is:

![image](https://github.com/caronc/apprise-api/assets/138012112/adcf4d9c-e2ca-4567-b64c-1bf862c52fb8)

Now if I use the cli with docker it works correctly:

```bash
docker container exec -it apprise-api apprise --body="Test Message" \
    apprises://appr.domain.tld/apprise/?tags=all \
    --attach=https://raw.githubusercontent.com/caronc/apprise/master/apprise/assets/themes/default/apprise-logo.png 
```

![image](https://github.com/caronc/apprise-api/assets/138012112/f74a42fc-ebad-4ee7-8bd1-03dfe0375cad)

I also tried with json , the result is that the message still does not appear:

```bash
    curl -X POST -d '{"body":"Test message","title":"Test Title", "attach": "https://raw.githubusercontent.com/caronc/apprise/master/apprise/assets/themes/default/apprise-logo.png "}' \
    -H "Content-Type: application/json" \
    "https://appr.domain.tld/notify/apprise?tags=all"
```

![image](https://github.com/caronc/apprise-api/assets/138012112/1f8c0e33-800b-40a3-a3c9-939bf89f945a)

**Comment by caronc** [comment] 2024-02-18 01:37
So upon investigating this more, i think the issue is the confusion around the word `attach`, you should be using `attachment` when just passing through the API.

However, when using `curl`'s `@` switch basically over-rides the `-F` variable assignment and identifies it as a file (and no longer becomes part of the payload itself.
```bash
# Using -F (it doesn't matter what it's called); this works:
curl -X POST \
    -F 'body=test message' \
    -F attach=@Screenshot-1.png \
    "https://appr.domain.tld/notify/apprise?tags=all"

# This does too:
curl -X POST \
    -F 'body=test message' \
    -F file=@Screenshot-1.png \
    "https://appr.domain.tld/notify/apprise?tags=all"

# and this does to; the thing is the @ with curl takes that variable and creates a new
# file/type section of the payload.  In the below, only `body` gets pass
curl -X POST \
    -F 'body=test message' \
    -F anything=@Screenshot-1.png \
    -F another=@Screenshot-2.png \
    "https://appr.domain.tld/notify/apprise?tags=all"
```

Now... when just passing using the API Payload, you must use `attachment` variable.  Here is some of the examples you used (but fixed):
```bash
   # JSON Version
   curl -X POST -d '{"body":"Test message","title":"Test Title", "attachment": "https://raw.githubusercontent.com/caronc/apprise/master/apprise/assets/themes/default/apprise-logo.png "}' \
    -H "Content-Type: application/json" \
    "https://appr.domain.tld/notify/apprise?tags=all"

  # Form Version
curl -X POST \
    -F 'body=test message' \
    -F 'attachment=https://raw.githubusercontent.com/caronc/apprise/master/apprise/assets/themes/default/apprise-logo.png' \
    http://localhost:8000/notify/{key}/
```

Let me know if this helps :rocket:

**Comment by caronc** [comment] 2024-02-18 02:10
I'm adding an `attach` keyword to just act as an alias of `attachment`; this will help with the confusion i think a bit.

**Comment by GMNDS** [comment] 2024-02-20 02:35
Thanks for the example, I must have missed this information in the documentation.

It's working perfectly, thank you.

**Comment by caronc** [comment] 2024-02-20 02:37
Great, closing this ticket off as complete

**Closed by caronc** 2024-02-20 02:37 UTC
Labels: question
