### ISSUE TITLE
Implement the Wiki within the App Dashboard

### ISSUE THREAD

**Issue by compgeniuses** [caronc/apprise-api#54] opened 2021-10-27 12:06 UTC
:bulb: **The Idea**

I installed this application on a server, and its a nice straight forward experience and what its trying to achieve, However, i noticed that for most things being referenced within the app, are always redirected back to the wiki here on GitHub.
:hammer: **Breaking Feature**

I believe it will make the usability much better if the wiki could be pre-loaded within the app, so that when someone wants to refer to something, they are directed to a wiki within the application, but not one hosted externally.
You could also provide a function to update the wiki as the software updates.

**Comment by caronc** [comment] 2021-10-31 20:11
I'll need to think about this. The direction I eventually wanted to go was to create a small javascript plugin that you could use to construct a URL with.  So first you might select the service (such as Discord, Slack, etc).  After you do that, dynamically t would help you build the URL by providing you the fields you need to obtain.   When you're all done and click 'Save' it would write it back as an additional entry on the Configuration Tab (something like that).

The problem is i'm not very good with JavaScript.  But the API needed to dynamically build the widget is already available (and built right into Apprise today).  It's just a matter of building a presentation tool with it.

As far as saving the documentation offline, that's an option too.  You can acquire it today by simply checking out the wiki as it is now:
```bash
# Clone the Apprise Wiki:
git clone https://github.com/apprise/apprise.wiki.git
```

**Comment by compgeniuses** [comment] 2021-11-02 09:22
wiil doing the git clone, integrate the wiki into the installed dashboard?

**Comment by caronc** [comment] 2021-11-02 17:16
No, it's just a means of getting the wiki offline. 🙂

Your actual request would actually involve some work. I was just trying to offer you some suggestions.

The thing with the API too is once you've set your URLs up, you don't normally go back to change them (not often anyway).

**Comment by caronc** [comment] 2022-05-29 21:14
Apprise is always getting bigger and supporting more and more new services.  It would be hard to merge 1 service into the other. I also want Apprise-API to operate without the need of the internet (as it could host local services too that are only available in your local network (such as kodi, etc).

I"m going to close this ticket as I don't see a need.  There is a link in the API to get the latest services and their howto.

In the future, i think what would be a good idea is a URL builder (that allows the user to pick the service, and then just fill out a form of some kind and let the builder construct the URL for you). 

Unfortunately I'm going to close this ticket for as it's not something i plan on addressing.  I appreciate your feedback all the same though.

Sorry to take so long to give a final verdict.

**Closed by caronc** 2022-05-29 21:14 UTC
