### ISSUE TITLE
Add Prometheus Metrics

### ISSUE THREAD

**Issue by MarkCupitt** [caronc/apprise-api#155] opened 2023-12-03 05:45 UTC
:bulb: **The Idea**
In an enterprise environment, we would like to be able to monitor messages using Prometheus Metrics

This wudl let us monitor activity, efficiency and performance and scale as necessary

https://prometheus.github.io/client_python/getting-started/three-step-demo/

:hammer: **Breaking Feature**
DOnt think it would break anything,

**Comment by caronc** [comment] 2023-12-28 21:20
Duplicate of #143

**Closed** 2023-12-28 21:21 UTC
Labels: duplicate, enhancement
