### ISSUE TITLE
Cannot save configuration on Synology.

### ISSUE THREAD

**Issue by ptrsmk** [caronc/apprise-api#63] opened 2021-11-14 06:52 UTC
Configurations will not save.  I receive a cannot write to disk error: "There was an issue writing the configuration to disk. Check your file permissions and try again."

I attempted to run `chmod 777 /var/lib/apprise/config` in the terminal, but that directory does not exist.  After receiving that error, I went looking for it.  Indeed there is no apprise folder within /var/lib/.  Manually creating it and chmodding it does not resolve the error when attempting to save a configuration.

Running in Docker on Synology NAS running DSM 7.

docker run --name apprise2021 \
   -p 4884:8000 \
-v /volume1/docker/apprise:/config \
--restart always \
   -d caronc/apprise:latest

**Comment by caronc** [comment] 2021-11-19 00:27
I think the problem is that you're changing the permission of the wrong directory.  According to your example, you should be changing the file permissions of `/volume1/docker/apprise` instead inside your terminal (not `/var/lib/apprise/config`)

**Comment by caronc** [comment] 2022-03-07 21:47
Did you ever get this figured out?

**Comment by caronc** [comment] 2022-05-29 21:11
Closing issue due to lack in response.

**Closed by caronc** 2022-05-29 21:11 UTC
Labels: question
